FROM node:12

# workspace 
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# RUN npm run start:dev
# set env file .env.prod (selected file .env.prod)
# ENV NODE_ENV prod
# port 8081
EXPOSE 1235
CMD ["node", "dist/main"]