version: "3.6"
networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
  public-network:
    driver: bridge

services:
  db:
    image: mysql:5.7
    volumes:
      - "./data:/var/lib/mysql"
    ports:
    - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: chatdb
      MYSQL_ROOT_PASSWORD: 4ynT9Q8aAzb
      MYSQL_USER: livingos
      MYSQL_PASSWORD: 4ynT9Q8aAzb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    networks:
      - db-network

volumes:
  db_data:
